baseURL: https://malleable.systems/
languageCode: en-gb
title: Malleable Systems Lab
theme: ananke
enableRobotsTXT: true

params:
  custom_css:
    - css/forkawesome/fork-awesome.css
    - css/custom.css
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0/
  licenseName: CC BY-SA 4.0
  mainSections:
    - blog
  email: mailto:hello@malleable.systems
  twitter: https://twitter.com/malleablesys
  matrix: https://matrix.to/#/#malleable-systems:matrix.org
  github: https://github.com/malleable-systems
  source: https://github.com/malleable-systems/malleable.systems

social:
  twitter: malleablesys

permalinks:
  blog: /blog/:year/:month/:day/:title/
  tags: /blog/tags/:title/
  categories: /blog/categories/:title/
  pages: /:title/

markup:
  goldmark:
    renderer:
      unsafe: true
