baseURL = "https://malleable.systems/"
languageCode = "en-gb"
title = "Malleable Systems Lab"
theme = "ananke"

[params]
mainSections = ["blog"]
github = "https://github.com/malleable-systems"

[permalinks]
blog = "/blog/:year/:month/:day/:title/"
tags = "/blog/tags/:title/"
categories = "/blog/categories/:title/"
pages = "/:title/"
