baseURL = "https://malleable.systems/"
languageCode = "en-gb"
title = "Malleable Systems Lab"
theme = "ananke"

[params]
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"
licenseName = "Creative Commons"
mainSections = ["blog"]
github = "https://github.com/malleable-systems"
twitter = "https://twitter.com/malleablesys"

[permalinks]
blog = "/blog/:year/:month/:day/:title/"
tags = "/blog/tags/:title/"
categories = "/blog/categories/:title/"
pages = "/:title/"
